@url_dev = http://localhost:8080/api
### Create user
POST {{url_dev}}/register
Content-Type: application/json

{
    "userName": "haiche",
    "uass": "test1",
    "uuid": "test2",
    "fullName": "che lan hai",
    "Email": "haiche@gmail.com",
    "phoneNumber": "0208292992",
    "address": "Ho Chi Minh",
    # "dob": "{{CurrentDatetime}}",
    "profileUrl": "test3"
}

### Get user
GET {{url_dev}}/user/2
Content-Type: application/json

### Delete user
DELETE  {{url_dev}}/user/2
Content-Type: application/json




