@url_dev = http://localhost:8080/api
### Create user
POST {{url_dev}}/register
Content-Type: application/json

{
    "username": "haiche",
    "password": "Abc123;",
    "fullName": "AAaaaaaa",
    "dob": "2024-09-11T08:19:10.596+00:00", // test in postman
    "address": "Ho Chi Minh"
}



